[General]
name=hacker-theme
description=Um tema SDDM  hacker efeito de chuva digital da Matrix.
description=A hacker theme for SDDM with matrix effects
author=Qaddoumi
ForkAuthor=DFS
websiteFork=https://github.com/DionatanFelipe/sddm-hacker-theme/
websiteOriginal=https://github.com/Qaddoumi/sddm-hacker-theme
license=MIT
version=1.0
background=assets/background.png
fontfamily=JetBrainsMono Nerd Font Propo
type=color
color=#00ff9c
fontSize=14
QtVersion=6
cursorTheme=capitaine-cursors
